
name: Merge branch rel-8.0 with rel-7.4
on:
  push:
    branches:
      - rel-7.4
jobs:
  merge-8-0-with-rel-7-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: rel-7.4
      - name: Reset promotion branch
        run: |
          git fetch origin rel-7.4:rel-7.4
          git reset --hard rel-7.4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-merge/rel-7-4/${{github.run_number}}
          title: Merge branch rel-8.0 with rel-7.4
          body: This PR generated automatically to merge rel-8.0 with rel-7.4. Please review the changed files before merging to prevent any errors that may occur.
          reviewers: ${{github.actor}}
          token: ${{ github.token }}
